#!/usr/bin/env python3
"""
generate.py — reads the gitignored spillere/ roster CSVs and patches index.html.

What it writes to index.html:
  - Initials for every person (derived from name, never stored raw)
  - First name only for lagledere (role == admin OR born before 2015)
  - Birthday greeting on matching match-day(s), using first name only
  - NO date of birth, NO last names for players, NO attendance, NO notes

Run:  python3 generate.py
"""

import csv
import re
from datetime import date, timedelta
from pathlib import Path

ROOT  = Path(__file__).parent
INDEX = ROOT / 'index.html'

TEAM_FILES = {
    1: ROOT / 'spillere' / 'Oppsal 1 - Sheet0.csv',
    2: ROOT / 'spillere' / 'Oppsal 2 - Sheet0.csv',
}

# Tournament match days (used only for birthday cross-reference)
CUP_DATES = {
    'søndag':  date(2026, 7, 26),
    'mandag':  date(2026, 7, 27),
    'tirsdag': date(2026, 7, 28),
    'onsdag':  date(2026, 7, 29),
    'torsdag': date(2026, 7, 30),
    'fredag':  date(2026, 7, 31),
}

# First names to show first in the lagleder line for each team
PRIORITY_FIRST_NAME = {1: 'Knut Marius', 2: 'Anders'}

# Names whose "first name" is more than one token
COMPOUND_FIRST = {'Knut Marius Torjuul': 'Knut Marius'}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_initials(name: str) -> str:
    """First letter of each part. Hyphens count as word separators."""
    parts = re.split(r'[\s\-]+', name.strip())
    return ''.join(p[0].upper() for p in parts if p)


def get_first_name(name: str) -> str:
    return COMPOUND_FIRST.get(name, name.split()[0])


def birthday_on_cup_days(dob: date, first_name: str) -> dict:
    """Return {dag_name: message} for any cup day whose date matches the
    birthday month+day, or is the day after the birthday.
    The DOB year is never used beyond deciding which cup day matches."""
    out = {}
    for dag, cup_day in CUP_DATES.items():
        if dob.month == cup_day.month and dob.day == cup_day.day:
            out[dag] = f'Gratulerer med dagen, {first_name}!'
        prev = cup_day - timedelta(days=1)
        if dob.month == prev.month and dob.day == prev.day:
            out[dag] = f'Gratulerer med dagen i går, {first_name}!'
    return out


# ---------------------------------------------------------------------------
# Load rosters
# ---------------------------------------------------------------------------

def load_rosters():
    """
    Returns:
      spillere  — dict  init → {lag, rolle, navn?, prioritet?}
                  'navn' is present only for lagledere, and holds first name only.
      bursdag   — dict  dag_name → greeting string
    """
    spillere = {}
    bursdag  = {}

    for team_nr, path in TEAM_FILES.items():
        with open(path, newline='', encoding='utf-8') as f:
            for row in csv.DictReader(f):
                if row['Response'].strip() == 'Declined':
                    continue

                name = row['Name'].strip()
                dob  = date.fromisoformat(row['Date of birth'].strip())
                is_lagleder = dob.year < 2015

                init   = make_initials(name)
                fname  = get_first_name(name)

                entry = spillere.setdefault(init, {'lag': [], 'rolle': None})
                if team_nr not in entry['lag']:
                    entry['lag'].append(team_nr)

                if is_lagleder:
                    entry['rolle'] = 'lagleder'
                    entry['navn']  = fname          # first name only, no last name
                    prio = PRIORITY_FIRST_NAME.get(team_nr)
                    if prio and name.startswith(prio):
                        entry['prioritet'] = True
                else:
                    if entry['rolle'] is None:
                        entry['rolle'] = 'spiller'  # don't overwrite lagleder

                # Birthday check — month+day only, year is discarded after this line
                for dag, msg in birthday_on_cup_days(dob, fname).items():
                    if dag not in bursdag:
                        bursdag[dag] = msg

    return spillere, bursdag


# ---------------------------------------------------------------------------
# Render spillere JS block
# ---------------------------------------------------------------------------

def render_spillere_js(spillere: dict) -> str:
    lines = [
        '// Generated by generate.py — initials for all; first name for lagledere only.',
        'const spillere = {',
    ]

    def single_team(team_nr, rolle):
        return [(i, e) for i, e in spillere.items()
                if e['lag'] == [team_nr] and e['rolle'] == rolle]

    def multi_team():
        return [(i, e) for i, e in spillere.items() if len(e['lag']) > 1]

    def lagleder_key(item):
        _, e = item
        return (0 if e.get('prioritet') else 1, e.get('navn', ''))

    def fmt(init, e):
        lag_str = f"[{','.join(str(l) for l in e['lag'])}]"
        parts   = [f"lag:{lag_str}", f"rolle:'{e['rolle']}'"]
        if 'navn' in e:                      # lagledere only
            parts.append(f"navn:'{e['navn']}'")
        if e.get('prioritet'):
            parts.append('prioritet:true')
        return f"  '{init}':{{{', '.join(parts)}}},"

    for team_nr in [1, 2]:
        lines.append(f'  // --- Oppsal {team_nr} spillere ---')
        for item in sorted(single_team(team_nr, 'spiller'), key=lambda x: x[0]):
            lines.append(fmt(*item))
        lines.append(f'  // --- Oppsal {team_nr} lagledere ---')
        for item in sorted(single_team(team_nr, 'lagleder'), key=lagleder_key):
            lines.append(fmt(*item))

    shared = multi_team()
    if shared:
        lines.append('  // --- Same initials across teams ---')
        for item in sorted(shared, key=lambda x: x[0]):
            lines.append(fmt(*item))

    lines.append('};')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Patch index.html
# ---------------------------------------------------------------------------

def patch_html(spillere_js: str, bursdag: dict):
    html = INDEX.read_text(encoding='utf-8')

    # 1. Replace spillere block (including any preceding generator comment)
    html = re.sub(
        r'// (?:Generated by generate\.py|Oppsal 1 and 2 rosters|OSM appears)[^\n]*\n',
        '',
        html,
    )
    html = re.sub(
        r'const spillere = \{.*?\};',
        spillere_js,
        html,
        flags=re.DOTALL,
    )

    # 2. Remove all existing bursdag fields from kamper entries
    html = re.sub(r",\s*bursdag:'[^']*'", '', html)

    # 3. Add bursdag fields to entries whose dag matches
    for dag, msg in bursdag.items():
        html = re.sub(
            rf"(dag:'{re.escape(dag)}'[^}}]*arena:'[^']*')(}},?)",
            rf"\1, bursdag:'{msg}'\2",
            html,
        )

    # 4. Simplify getLagledereNavn — navn is now already the display name
    html = html.replace(
        "    .map(s => s.fornavn || s.navn.split(' ')[0]);",
        "    .map(s => s.navn);",
    )

    INDEX.write_text(html, encoding='utf-8')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    spillere, bursdag = load_rosters()
    spillere_js = render_spillere_js(spillere)

    print('=== spillere object (this is what goes into index.html) ===')
    print(spillere_js)
    print()
    print('=== bursdag messages ===')
    if bursdag:
        for dag, msg in bursdag.items():
            print(f'  {dag}: {msg!r}')
    else:
        print('  (none)')
    print()

    patch_html(spillere_js, bursdag)
    print('index.html patched.')


if __name__ == '__main__':
    main()
